# Question

Will the code work? Why or why not?

```js
const getUsers = async () => {
  const url = 'https://jsonplaceholder.typicode.com/users';
  const users = await fetch(url).then(r => r.json()).catch((err) => []);
  console.log(users)
  return users;
}
getUsers()
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer
yes this code would work because The catch block ensures that any errors during the fetch process result in an empty array. This prevents the code from crashing.

# Teacher Feedback